name: learning
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^5.0.0  # Ensure this version is compatible
  url_launcher: ^6.0.3  # Ensure this version is compatible
  font_awesome_flutter: ^10.8.0
  cv: ^1.1.3
  image_picker: ^0.8.7+5
  image: ^4.0.17
  path_provider: ^2.0.14
  #flutter_resume_template: ^1.2.1
  provider:
  pdf:
  shared_preferences:
  intl:
  printing:
  table_calendar: ^3.1.3
  get_storage: ^2.0.3
  settings_ui: ^2.0.2
  contactus: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Only use dependency_overrides if you need to override a package version locally
dependency_overrides:
  font_awesome_flutter:
flutter:
  uses-material-design: true
  assets:
    - assets/images/1.png  # Ensure this file exists in the specified path
    - assets/img/profile.png
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
